# Generated by Django 6.0.5 on 2026-06-01 00:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_name",
                    models.CharField(max_length=10, verbose_name="Currency Name"),
                ),
                (
                    "buy_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Buy Rate"
                    ),
                ),
                (
                    "sell_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Sell Rate"
                    ),
                ),
                (
                    "date_added",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date Added"
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency Rate",
                "verbose_name_plural": "Currency Rates",
                "ordering": ["-date_added", "currency_name"],
            },
        ),
    ]
